### ISSUE TITLE
undeclared (first use in this function); did you mean 'POLLING_INTERVAL', when dirty build total kernal

### ISSUE THREAD

**Issue by FlyInWind1** [coiby/standalone_i2c_hid#3]
I want to build total kernal with this patch. No problem with first build after make clean, but after change some code then build i get this error
![Screenshot_20201120_003614](https://user-images.githubusercontent.com/29172747/99695442-89e14600-2ac8-11eb-9954-7bb5ad8deac3.png)

**Comment by coiby** [comment]
The error is caused the driver `drivers/staging/rts5208`. If you don't use that driver, disable building that driver by commenting out the line `CONFIG_RTS5208=m` in `.config`. Or you can fix that driver by yourself.
