### ISSUE TITLE
Cannot make module after updating from 5.9.10-arch1-1 to 5.9.11-arch2-1

### ISSUE THREAD

**Issue by pm4rcin** [coiby/standalone_i2c_hid#4]
When I try to ```make``` module it doesn't compile.
1. ```cd standalone_i2c_hid/i2c-hid_standalone/```
2. ```make```
Output:
```make -C /lib/modules/`uname -r`/build M=`pwd`
make[1]: Wejście do katalogu (entering directory) '/usr/lib/modules/5.9.11-arch2-1/build'
make[1]: Opuszczenie katalogu (leaving directory) '/usr/lib/modules/5.9.11-arch2-1/build'```
3. ```sudo insmod i2c-hid.ko polling_mode=1```
Output: 
```insmod: ERROR: could not insert module i2c-hid.ko: Invalid module format```

**Comment by coiby** [comment]
Do you use secure boot? If yes, you can follow https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190/comments/233 to sign the module.

**Comment by pm4rcin** [comment]
No, the secure boot is disabled in BIOS.

**Comment by pm4rcin** [comment]
it's really weird but after updating to 5.9.13-arch1-1 the module can be build again and works.
