### ISSUE TITLE
doesn't stick on reboot

### ISSUE THREAD

**Issue by adiadi2** [coiby/standalone_i2c_hid#5]
Hi, as title says, I installed it and it's working as expected, but it doesen't stick on reboot (or shutown) so do you have any idea how to work that out?
I've tried to add "GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i2c_hid.polling_mode=1"" to grub file but it doesn't work.
BTW I'm on ubuntu 20.04 lts, 5.8.0-41-generic kernel
regards

**Comment by curzon01** [comment]
simply load it using e.g. `/etc/rc.local`:
```
cd /path/to/devfile/i2c-hid_standalone
rmmod i2c_hid
insmod i2c-hid.ko polling_mode=1
```

**Comment by adiadi2** [comment]
Hi, thanks for the advice, already did it with `systemd service

`[Unit]
Description=Fix for i2c-hid trackpad driver

[Service]
ExecStart=-rmmod i2c-hid
ExecStart=-insmod /lib/modules/5.8.0-41-generic/kernel/drivers/hid/i2c-hid/i2c-hid.ko polling_mode=1
Type=oneshot

[Install]
WantedBy=graphical.target
`

**Comment by coiby** [comment]
Hi

I've updated README.md, https://github.com/coiby/standalone_i2c_hid/blob/master/README.md#persist-after-rebooting provides another method to have persistent effect.

Btw, which laptop model do you use? The polling mode is supposed to be a backup solution. Hopefully, the root cause could be fixed later.

**Comment by curzon01** [comment]
mine is a Lenovo Legion 5 15ARH05 with MSFT0001:00 04F3:3140 Touchpad

if loading driver manualy without polling doesn't work

**Comment by coiby** [comment]
> mine is a Lenovo Legion 5 15ARH05 with MSFT0001:00 04F3:3140 Touchpad
> 
> if loading driver manualy without polling doesn't work

The root cause for Lenovo Legion 5 15ARH05 with MSFT0001:00 04F3:3140 Touchpad has been fixed. Please check the bug description of https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190.

**Comment by curzon01** [comment]
I'm using latest commit (12h ago) from here and there are 126 matches in the bug thread having "04F3:3140" :confused:

**Comment by coiby** [comment]
On Mon, Feb 01, 2021 at 03:31:38AM -0800, Norbert Richter wrote:
>I'm using latest commit (12h ago) from here and there are 126 matches in the bug thread having "04F3:3140" :confused:

Just follow the guidance in the bug description. Basically, you should
use patched pinctrl-amd driver.

**Comment by adiadi2** [comment]
@coiby mine is a Lenovo Legion 5 15ARH05H, ryzen 5 4600H, GTX 1660ti mobile with MSFT0001:00 06CB:7F28 Touchpad, does that fix also apply to my model. I just need to follow your post #189 right?
update: and this is mine modinfo
modinfo pinctrl-amd
name:           pinctrl_amd
filename:       (builtin)
description:    AMD GPIO pinctrl driver
author:         Ken Xue <Ken.Xue@amd.com>, Jeff Wu <Jeff.Wu@amd.com>
license:        GPL v2
file:           drivers/pinctrl/pinctrl-amd

**Comment by adiadi2** [comment]
@coiby and I can't find pinctrl-amd.ko.xz or pinctrl-amd.ko anywhere, there's no pinctrl-amd dir under kernel/drivers dir,
just a line "kernel/drivers/pinctrl/pinctrl-amd.ko" inside /lib/modules/5.8.0-41-generic/modules.builtin file?

**Comment by adiadi2** [comment]
oh, I found your #205 on https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190 about this issue.

**Comment by coiby** [comment]
> mine is a Lenovo Legion 5 15ARH05H, ryzen 5 4600H, GTX 1660ti mobile with MSFT0001:00 06CB:7F28 Touchpad, does that fix also apply to my model. I just need to follow your post #189 right?

Yes, Linux kernel 5.11 has the fix for the laptop.

>oh, I found your #205 on https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190 about this issue.

Oh, then you have to re-build the kernel. Or maybe your distribution has
provides Linux kernel 5.11 for testing and you can give it a try to
avoid building the kernel by yourself.

**Comment by adiadi2** [comment]
I've tried mainline 5.11 rc5 before your standalone i2c, it was working, but reinstaled the system since  I had some error messages on boot and wasn't sure of the cause, was it tampering with kernel or more probably, since it"s dual boot win10 and ubuntu, the fact that I unknowingly installed windows on uefi and ubutu on bios, and didn't know how to make nvidia driver to work with 5.11. Since it was my third reinstall in a month and nvidia driver problems I decided to stick with stock kernel and wait for official fix and use your workaround untill than or untill I gain some more linux knowledge.
What's your opinion about a timeframe root cause fix gets into official kernel?
Thanks

**Comment by coiby** [comment]
On Tue, Feb 02, 2021 at 09:39:42AM -0800, adiadi2 wrote:
>I've tried mainline 5.11 rc5 before your standalone i2c, it was working, but reinstaled the system since  I had some error messages on boot and wasn't sure of the cause, was it tampering with kernel or more probably, since it"s dual boot win10 and ubuntu, the fact that I unknowingly installed windows on uefi and ubutu on bios, and didn't know how to make nvidia driver to work with 5.11. Since it was my third reinstall in a month and nvidia driver problems I decided to stick with stock kernel and wait for official fix and use your workaround untill than or untill I gain some more linux knowledge.
>What's your opinion about a timeframe root cause fix gets into official kernel?
>Thanks

According to [1], "the final release of Linux Kernel 5.11 is said to be
expected in mid-February". But even Linux 5.11 is released, different
distribution may need time to release the built binary package. It
seems, the best choice is to use this standalone i2c on 5.10 before the
release of the binary kernel 5.11 package.

[1] https://www.seeedstudio.com/blog/2020/12/29/linux-kernel-5-11-release-candidate-announced-with-more-features-and-improvements/
